#! /bin/sh
# /etc/init.d/beagleboard-wifi-conf

### BEGIN INIT INFO
# Provides:          beagleboard-wifi-conf
# Required-Start:    $local_fs $syslog $network
# Required-Stop:     $local_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Script to ensure wifi connectivity
# Description:       A NodeJS application to ensure Wifi connectivity by setting the RPI as an AP if needed
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting beagleboard-wifi-conf service"
    cd /home/debian/beagleboard-wifi-conf
    sudo /usr/bin/node server.js &
    echo $! > node.pid
    ;;
  stop)
    echo "Stopping beagleboard-wifi-conf service"
    PIDFile=/home/debian/beagleboard-wifi-conf/node.pid
    if [ -f $PIDFile ]; then
        sudo kill -9 $(cat $PIDFile)
        sudo kill -9 $(($(cat $PIDFile) + 1))
        sudo rm $PIDFile
    fi
    ;;
  *)
    echo "Usage: /etc/init.d/beagleboard-wifi-conf {start|stop}"
    exit 1
    ;;
esac

exit 0
